### ISSUE TITLE
Разделить исходный код на функции

### ISSUE THREAD

**Issue by andrey-ilyin** [Marillinnka/Backend#1]
Прошу разделить исходный код на логические блоки и выделить их в функции.

**Comment by andrey-ilyin** [comment]
Разделение надо сделать и в первой, и во второй лабораторных работах.

**Comment by Marillinnka** [comment]
Первую лабораторную поправила и разбила исходный код на функции.
По поводу второй лабы, суть задания состояла в проектировании классов, т.е. в классах и так всё разбито на методы. Файл Program.cs - код для тестирования  работоспособности программы, на лекции обговаривалось, что данный файл можно оставить пустым, я заполнила его для того, чтобы проверить, что программа рабочая, следовательно его содержимое не нуждается в разбиении на функции.

**Comment by andrey-ilyin** [comment]
Основной код программы по прежнему достаточно большой. 
Необходимо ещё разделение на функции.

**Comment by Marillinnka** [comment]
Ещё раз разбила основной код на функции.
